package panels;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author felip
 */
public class AgregarPanel extends javax.swing.JPanel {

    ArrayList<Cancion> listaCanciones = new ArrayList();

    /**
     * Creates new form AgregarPanel
     */
    public AgregarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblAutor = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtDisco = new javax.swing.JTextField();
        txtDuracionSeg = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtDuracionMin = new javax.swing.JTextField();
        lblDuracion = new javax.swing.JLabel();
        txtEstilo = new javax.swing.JTextField();
        lblEstilo = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        lblDuracionSeg = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        btnEnviar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblAgregarCanciones = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(234, 246, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAutor.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblAutor.setForeground(new java.awt.Color(11, 19, 43));
        lblAutor.setText("Autor");
        bg.add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, 20));

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(11, 19, 43));
        lblTitulo.setText("Titulo");
        bg.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, 20));

        txtTitulo.setBackground(new java.awt.Color(234, 246, 255));
        txtTitulo.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtTitulo.setBorder(null);
        bg.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 150, 30));

        txtDisco.setBackground(new java.awt.Color(234, 246, 255));
        txtDisco.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtDisco.setBorder(null);
        bg.add(txtDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 160, 30));

        txtDuracionSeg.setBackground(new java.awt.Color(234, 246, 255));
        txtDuracionSeg.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtDuracionSeg.setBorder(null);
        bg.add(txtDuracionSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, 30));

        lblID.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblID.setForeground(new java.awt.Color(11, 19, 43));
        lblID.setText("ID");
        bg.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 160, 20));

        txtID.setBackground(new java.awt.Color(234, 246, 255));
        txtID.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtID.setBorder(null);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        bg.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 160, 30));

        lblResultado.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(11, 19, 43));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 580, 30));

        txtAutor.setBackground(new java.awt.Color(234, 246, 255));
        txtAutor.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtAutor.setBorder(null);
        bg.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, 30));

        txtDuracionMin.setBackground(new java.awt.Color(234, 246, 255));
        txtDuracionMin.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtDuracionMin.setBorder(null);
        txtDuracionMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionMinActionPerformed(evt);
            }
        });
        bg.add(txtDuracionMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 150, 30));

        lblDuracion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(11, 19, 43));
        lblDuracion.setText("Duración(min.)");
        bg.add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 160, 20));

        txtEstilo.setBackground(new java.awt.Color(234, 246, 255));
        txtEstilo.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtEstilo.setBorder(null);
        bg.add(txtEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 160, 30));

        lblEstilo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblEstilo.setForeground(new java.awt.Color(11, 19, 43));
        lblEstilo.setText("Estilo");
        bg.add(lblEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 160, 20));

        txtAño.setBackground(new java.awt.Color(234, 246, 255));
        txtAño.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtAño.setBorder(null);
        bg.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 160, 30));

        lblAño.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblAño.setForeground(new java.awt.Color(11, 19, 43));
        lblAño.setText("Año");
        bg.add(lblAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 50, 20));

        lblDuracionSeg.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblDuracionSeg.setForeground(new java.awt.Color(11, 19, 43));
        lblDuracionSeg.setText("Duracion (seg.)");
        bg.add(lblDuracionSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 250, 20));

        lblDisco.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblDisco.setForeground(new java.awt.Color(11, 19, 43));
        lblDisco.setText("Disco");
        bg.add(lblDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 160, 20));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 160, 10));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 150, 10));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, 10));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 150, 10));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 160, 10));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 150, 10));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 160, 10));
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 160, 10));

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_enviar.png"))); // NOI18N
        btnEnviar.setBorderPainted(false);
        btnEnviar.setContentAreaFilled(false);
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_enviar_sel.png"))); // NOI18N
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        bg.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 200, 50));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_limpiar.png"))); // NOI18N
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_limpiar_sel.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        bg.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 200, 50));

        lblAgregarCanciones.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblAgregarCanciones.setForeground(new java.awt.Color(11, 19, 43));
        lblAgregarCanciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarCanciones.setText("Agregar Canciones");
        bg.add(lblAgregarCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 580, 30));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuracionMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionMinActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        Cancion cancionAux = new Cancion();

        cancionAux.setId_cancion(Integer.parseInt(txtID.getText()));
        cancionAux.setTitulo(txtTitulo.getText());
        cancionAux.setAutor(txtAutor.getText());
        cancionAux.setDisco(txtDisco.getText());
        cancionAux.setAnio(Integer.parseInt(txtAño.getText()));
        cancionAux.setDuracion_minuto(Integer.parseInt(txtDuracionMin.getText()));
        cancionAux.setDuracion_segundo(Integer.parseInt(txtDuracionSeg.getText()));
        cancionAux.setEstilo(txtEstilo.getText());

        if (listaCanciones.add(cancionAux)) {
            lblResultado.setText("Cancion Agregada Exitosamente!");
        } else {
            lblResultado.setText("No Agrego Correctamente!");
        }
        try {
            insertarCancionEnDB(cancionAux);
        } catch (SQLException ex) {
            Logger.getLogger(AgregarPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        txtDisco.setText("");
        txtAño.setText("");
        txtDuracionMin.setText("");
        txtDuracionSeg.setText("");
        txtEstilo.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAgregarCanciones;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblDuracionSeg;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDisco;
    private javax.swing.JTextField txtDuracionMin;
    private javax.swing.JTextField txtDuracionSeg;
    private javax.swing.JTextField txtEstilo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    public static void insertarCancionEnDB(Cancion cancion) throws SQLException {
        // Configuración de la conexión a la base de datos
        String url = "jdbc:mysql://localhost:3306/wurlitzerdb";
        String usuario = "root";
        String contraseña = "";

        // Establecer la conexión
        Connection conexion = DriverManager.getConnection(url, usuario, contraseña);
        // Crear la sentencia SQL para la inserción
        String sql = "INSERT INTO cancion (id_cancion, titulo, autor, disco, año, duracion_minuto, duracion_segundo, estilo) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement preparedStatement = conexion.prepareStatement(sql)) {
            // Establecer los valores de los parámetros
            preparedStatement.setInt(1, cancion.getId_cancion());
            preparedStatement.setString(2, cancion.getTitulo());
            preparedStatement.setString(3, cancion.getAutor());
            preparedStatement.setString(4, cancion.getDisco());
            preparedStatement.setInt(5, cancion.getAnio());
            preparedStatement.setInt(6, cancion.getDuracion_minuto());
            preparedStatement.setInt(7, cancion.getDuracion_segundo());
            preparedStatement.setString(8, cancion.getEstilo());

            // Ejecutar la inserción
            preparedStatement.executeUpdate();

            System.out.println("Canción insertada correctamente en la base de datos.");
        }
    }
}
