package panels;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Cetecom
 */
public class Conectar extends javax.swing.JFrame {
    //Instanciar un objeto de clase Connection
    private static Connection con;
    //Declarar variables para realizar conexion
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    //Variables Barra Ventana
    int xMouse, yMouse;
    //Url de la base de datos (Revisar si el puerto corresponde)
    private static final String url = "jdbc:mysql://localhost:3306/wurlitzerdb";

    //Funcion conectar
    public void Conectar() {
        //Se vacia el objeto Connection
        con = null;
        //Try catch para capturar los errores
        try {
            Class.forName(driver);
            // Nos conectamos a la bd (Volver a escribir los atributos en caso de que arroje error)
            //Se importa DriverManager
            con = (Connection) DriverManager.getConnection(url, user, pass);
            // Si la conexion fue exitosa mostramos un mensaje de conexion exitosa
            if (con != null) {
                lblResultado.setText("Conexion establecida");
            }
        } // Si la conexion NO fue exitosa mostramos un mensaje de error
        //Se importa SQLException
        catch (ClassNotFoundException | SQLException e) {
            lblResultado.setText("Error de conexion" + e);
        }
    }

    /**
     * Creates new form Conectar
     */
    public Conectar() {
        initComponents();

        Principal agPn = new Principal();
        agPn.setSize(800, 600);
        agPn.setLocation(0, 0);
        this.setResizable(false);
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));

        Agregar.removeAll();
        Agregar.add(agPn, BorderLayout.CENTER);
        Agregar.revalidate();
        Agregar.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        bgTitle = new javax.swing.JPanel();
        lblWulritzer = new javax.swing.JLabel();
        bgAgregar = new panels.PanelRound();
        lblAgregar = new javax.swing.JLabel();
        bgEliminar = new panels.PanelRound();
        lblEliminar = new javax.swing.JLabel();
        bgModificar = new panels.PanelRound();
        lblModificar = new javax.swing.JLabel();
        bgMostrar = new panels.PanelRound();
        lblMostrar = new javax.swing.JLabel();
        bgSolicitar = new panels.PanelRound();
        lblSolicitar = new javax.swing.JLabel();
        bgConectar = new panels.PanelRound();
        lblConectar = new javax.swing.JLabel();
        panelVentana = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar.setBackground(new java.awt.Color(234, 246, 255));
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setMaximumSize(new java.awt.Dimension(400, 600));
        Agregar.setMinimumSize(new java.awt.Dimension(400, 600));
        Agregar.setPreferredSize(new java.awt.Dimension(400, 600));

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar);
        Agregar.setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 580, 570));

        bg.setBackground(new java.awt.Color(36, 123, 160));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResultado.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 255));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("Estado");
        bg.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 220, 30));

        bgTitle.setBackground(new java.awt.Color(28, 37, 65));

        lblWulritzer.setBackground(new java.awt.Color(28, 37, 65));
        lblWulritzer.setFont(new java.awt.Font("Roboto Black", 1, 27)); // NOI18N
        lblWulritzer.setForeground(new java.awt.Color(255, 255, 255));
        lblWulritzer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWulritzer.setText("WURLITZER DB");
        lblWulritzer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblWulritzer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWulritzerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblWulritzerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblWulritzerMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblWulritzerMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout bgTitleLayout = new javax.swing.GroupLayout(bgTitle);
        bgTitle.setLayout(bgTitleLayout);
        bgTitleLayout.setHorizontalGroup(
            bgTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWulritzer, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        bgTitleLayout.setVerticalGroup(
            bgTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWulritzer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg.add(bgTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        bgAgregar.setBackground(new java.awt.Color(28, 37, 65));
        bgAgregar.setRoundBottomLeft(55);
        bgAgregar.setRoundBottomRight(55);
        bgAgregar.setRoundTopLeft(55);
        bgAgregar.setRoundTopRight(55);
        bgAgregar.setLayout(null);

        lblAgregar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setText("Agregar");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAgregarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAgregarMouseReleased(evt);
            }
        });
        bgAgregar.add(lblAgregar);
        lblAgregar.setBounds(0, 0, 200, 50);

        bg.add(bgAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 50));

        bgEliminar.setBackground(new java.awt.Color(28, 37, 65));
        bgEliminar.setRoundBottomLeft(55);
        bgEliminar.setRoundBottomRight(55);
        bgEliminar.setRoundTopLeft(55);
        bgEliminar.setRoundTopRight(55);
        bgEliminar.setLayout(null);

        lblEliminar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("Eliminar");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblEliminarMouseReleased(evt);
            }
        });
        bgEliminar.add(lblEliminar);
        lblEliminar.setBounds(0, 0, 200, 50);

        bg.add(bgEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 50));

        bgModificar.setBackground(new java.awt.Color(28, 37, 65));
        bgModificar.setRoundBottomLeft(55);
        bgModificar.setRoundBottomRight(55);
        bgModificar.setRoundTopLeft(55);
        bgModificar.setRoundTopRight(55);
        bgModificar.setLayout(null);

        lblModificar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificar.setText("Modificar");
        lblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModificarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblModificarMouseReleased(evt);
            }
        });
        bgModificar.add(lblModificar);
        lblModificar.setBounds(0, 0, 200, 50);

        bg.add(bgModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 200, 50));

        bgMostrar.setBackground(new java.awt.Color(28, 37, 65));
        bgMostrar.setRoundBottomLeft(55);
        bgMostrar.setRoundBottomRight(55);
        bgMostrar.setRoundTopLeft(55);
        bgMostrar.setRoundTopRight(55);
        bgMostrar.setLayout(null);

        lblMostrar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblMostrar.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrar.setText("Mostrar");
        lblMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMostrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMostrarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblMostrarMouseReleased(evt);
            }
        });
        bgMostrar.add(lblMostrar);
        lblMostrar.setBounds(0, 0, 200, 50);

        bg.add(bgMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 50));

        bgSolicitar.setBackground(new java.awt.Color(28, 37, 65));
        bgSolicitar.setRoundBottomLeft(55);
        bgSolicitar.setRoundBottomRight(55);
        bgSolicitar.setRoundTopLeft(55);
        bgSolicitar.setRoundTopRight(55);
        bgSolicitar.setLayout(null);

        lblSolicitar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblSolicitar.setForeground(new java.awt.Color(255, 255, 255));
        lblSolicitar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSolicitar.setText("Solicitar");
        lblSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSolicitarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSolicitarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSolicitarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblSolicitarMouseReleased(evt);
            }
        });
        bgSolicitar.add(lblSolicitar);
        lblSolicitar.setBounds(0, 0, 200, 50);

        bg.add(bgSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, 50));

        bgConectar.setBackground(new java.awt.Color(28, 37, 65));
        bgConectar.setRoundBottomLeft(40);
        bgConectar.setRoundBottomRight(40);
        bgConectar.setRoundTopLeft(40);
        bgConectar.setRoundTopRight(40);
        bgConectar.setLayout(null);

        lblConectar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblConectar.setForeground(new java.awt.Color(255, 255, 255));
        lblConectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConectar.setText("Conectar");
        lblConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConectarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblConectarMouseReleased(evt);
            }
        });
        bgConectar.add(lblConectar);
        lblConectar.setBounds(0, 0, 140, 40);

        bg.add(bgConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 140, 40));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        panelVentana.setBackground(new java.awt.Color(234, 246, 255));
        panelVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelVentanaMouseDragged(evt);
            }
        });
        panelVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelVentanaMousePressed(evt);
            }
        });

        lblSalir.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(28, 37, 65));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("X");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });

        lblMinimizar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(28, 37, 65));
        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setText("_");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelVentanaLayout = new javax.swing.GroupLayout(panelVentana);
        panelVentana.setLayout(panelVentanaLayout);
        panelVentanaLayout.setHorizontalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentanaLayout.createSequentialGroup()
                .addContainerGap(747, Short.MAX_VALUE)
                .addComponent(lblMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSalir)
                .addGap(17, 17, 17))
        );
        panelVentanaLayout.setVerticalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSalir))
            .addGroup(panelVentanaLayout.createSequentialGroup()
                .addComponent(lblMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVentanaMousePressed
        // TODO add your handling code here:
        //Asigna valores actuales a variables de posicion del mouse
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelVentanaMousePressed

    private void panelVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVentanaMouseDragged
        // TODO add your handling code here:
        //Asigna posicion del mouse en la pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Mueve ventana a la posicion del mouse
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelVentanaMouseDragged

    private void lblWulritzerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWulritzerMouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_lblWulritzerMouseClicked

    private void lblWulritzerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWulritzerMouseEntered
        // TODO add your handling code here:
        bgTitle.setBackground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblWulritzerMouseEntered

    private void lblWulritzerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWulritzerMouseExited
        // TODO add your handling code here:
        bgTitle.setBackground(new Color(0x1C2541));
    }//GEN-LAST:event_lblWulritzerMouseExited

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        // TODO add your handling code here:    
    }//GEN-LAST:event_lblAgregarMouseClicked

    private void lblAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseEntered
        // TODO add your handling code here:
        bgAgregar.setBackground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblAgregarMouseEntered

    private void lblAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseExited
        // TODO add your handling code here:
        bgAgregar.setBackground(new Color(0x1C2541));
    }//GEN-LAST:event_lblAgregarMouseExited

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseEntered
        // TODO add your handling code here:
        bgEliminar.setBackground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblEliminarMouseEntered

    private void lblEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseExited
        // TODO add your handling code here:
        bgEliminar.setBackground(new Color(0x1C2541));
    }//GEN-LAST:event_lblEliminarMouseExited

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseEntered
        // TODO add your handling code here:
        bgModificar.setBackground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblModificarMouseEntered

    private void lblModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseExited
        // TODO add your handling code here:
        bgModificar.setBackground(new Color(0x1C2541));
    }//GEN-LAST:event_lblModificarMouseExited

    private void lblMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMostrarMouseClicked

    private void lblMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseEntered
        // TODO add your handling code here:
        bgMostrar.setBackground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblMostrarMouseEntered

    private void lblMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseExited
        // TODO add your handling code here:
        bgMostrar.setBackground(new Color(0x1C2541));
    }//GEN-LAST:event_lblMostrarMouseExited

    private void lblSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSolicitarMouseClicked

    private void lblSolicitarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitarMouseEntered
        // TODO add your handling code here:
        bgSolicitar.setBackground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblSolicitarMouseEntered

    private void lblSolicitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitarMouseExited
        // TODO add your handling code here:
        bgSolicitar.setBackground(new Color(0x1C2541));
    }//GEN-LAST:event_lblSolicitarMouseExited

    private void lblConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConectarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConectarMouseClicked

    private void lblConectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConectarMouseEntered
        // TODO add your handling code here:
        bgConectar.setBackground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblConectarMouseEntered

    private void lblConectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConectarMouseExited
        // TODO add your handling code here:
        bgConectar.setBackground(new Color(0x1C2541));
    }//GEN-LAST:event_lblConectarMouseExited

    private void lblAgregarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseReleased
        // TODO add your handling code here:
        AgregarPanel agPn = new AgregarPanel();
        agPn.setSize(580, 570);
        agPn.setLocation(0, 0);

        Agregar.removeAll();
        Agregar.add(agPn, BorderLayout.CENTER);
        Agregar.revalidate();
        Agregar.repaint();  
    }//GEN-LAST:event_lblAgregarMouseReleased

    private void lblEliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseReleased
        // TODO add your handling code here:
        Eliminar agPn = new Eliminar();
        agPn.setSize(580, 570);
        agPn.setLocation(0, 0);

        Agregar.removeAll();
        Agregar.add(agPn, BorderLayout.CENTER);
        Agregar.revalidate();
        Agregar.repaint(); 
    }//GEN-LAST:event_lblEliminarMouseReleased

    private void lblMostrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseReleased
        // TODO add your handling code here:
        MostrarPanel mosPn = new MostrarPanel();
        mosPn.setSize(580, 570);
        mosPn.setLocation(0, 0);

        Agregar.removeAll();
        Agregar.add(mosPn, BorderLayout.CENTER);
        Agregar.revalidate();
        Agregar.repaint();
    }//GEN-LAST:event_lblMostrarMouseReleased

    private void lblModificarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseReleased
        // TODO add your handling code here:
        Modificar moPn = new Modificar();
        moPn.setSize(580, 570);
        moPn.setLocation(0, 0);

        Agregar.removeAll();
        Agregar.add(moPn, BorderLayout.CENTER);
        Agregar.revalidate();
        Agregar.repaint();
    }//GEN-LAST:event_lblModificarMouseReleased

    private void lblSolicitarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitarMouseReleased
        // TODO add your handling code here:
        Solicitar agPn = new Solicitar();
        agPn.setSize(580, 570);
        agPn.setLocation(0, 0);

        Agregar.removeAll();
        Agregar.add(agPn, BorderLayout.CENTER);
        Agregar.revalidate();
        Agregar.repaint();
    }//GEN-LAST:event_lblSolicitarMouseReleased

    private void lblConectarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConectarMouseReleased
        // TODO add your handling code here:
        Conectar();
    }//GEN-LAST:event_lblConectarMouseReleased

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        // TODO add your handling code here:
        lblSalir.setForeground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        // TODO add your handling code here:
        lblSalir.setForeground(new Color(0x1C2541));
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Conectar.ICONIFIED);

    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseEntered
        // TODO add your handling code here:
        lblMinimizar.setForeground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblMinimizarMouseEntered

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        // TODO add your handling code here:
        lblMinimizar.setForeground(new Color(0x1C2541));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblWulritzerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWulritzerMouseReleased
        // TODO add your handling code here:
        Principal agPn = new Principal();
        agPn.setSize(580, 570);
        agPn.setLocation(0, 0);

        Agregar.removeAll();
        Agregar.add(agPn, BorderLayout.CENTER);
        Agregar.revalidate();
        Agregar.repaint();     
    }//GEN-LAST:event_lblWulritzerMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //Desactiva escalado automatico de Swing
        System.setProperty("sun.java2d.uiScale", "1.0");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conectar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar;
    private javax.swing.JPanel bg;
    private panels.PanelRound bgAgregar;
    private panels.PanelRound bgConectar;
    private panels.PanelRound bgEliminar;
    private panels.PanelRound bgModificar;
    private panels.PanelRound bgMostrar;
    private panels.PanelRound bgSolicitar;
    private javax.swing.JPanel bgTitle;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblConectar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblSolicitar;
    private javax.swing.JLabel lblWulritzer;
    private javax.swing.JPanel panelVentana;
    // End of variables declaration//GEN-END:variables
}
