package panels;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLayeredPane;
import javax.swing.JList;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author felip
 */
public class Modificar extends javax.swing.JPanel {

    ArrayList<Cancion> listaCanciones = new ArrayList<>();
    private DefaultListModel<String> listModelJList;

    /**
     * Creates new form ModificarPanel
     */
    public Modificar() {
        initComponents();
        listModelJList = new DefaultListModel<>();
        JListCanciones.setModel(listModelJList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListCanciones = new javax.swing.JList<>();
        btnMostrar = new javax.swing.JButton();
        lblModificar = new javax.swing.JLabel();
        bgModificar = new panels.PanelRound();
        lblModificar1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(225, 245, 254));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar.setBackground(new java.awt.Color(234, 246, 255));
        Agregar.setLayout(null);

        JListCanciones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        JListCanciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JListCanciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JListCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(JListCanciones);

        Agregar.add(jScrollPane1);
        jScrollPane1.setBounds(50, 120, 480, 360);

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnMostrar.setBorder(null);
        btnMostrar.setBorderPainted(false);
        btnMostrar.setContentAreaFilled(false);
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh _sel.png"))); // NOI18N
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        Agregar.add(btnMostrar);
        btnMostrar.setBounds(500, 90, 24, 24);

        lblModificar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(11, 19, 43));
        lblModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificar.setText("Selecciona una canción");
        Agregar.add(lblModificar);
        lblModificar.setBounds(0, 40, 574, 30);

        bgModificar.setBackground(new java.awt.Color(28, 37, 65));
        bgModificar.setRoundBottomLeft(55);
        bgModificar.setRoundBottomRight(55);
        bgModificar.setRoundTopLeft(55);
        bgModificar.setRoundTopRight(55);
        bgModificar.setLayout(null);

        lblModificar1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblModificar1.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificar1.setText("Modificar");
        lblModificar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblModificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModificar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModificar1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblModificar1MouseReleased(evt);
            }
        });
        bgModificar.add(lblModificar1);
        lblModificar1.setBounds(0, 0, 200, 50);

        Agregar.add(bgModificar);
        bgModificar.setBounds(190, 500, 200, 50);

        add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        listaCanciones.clear();
        try {
            String url = "jdbc:mysql://localhost:3306/wurlitzerdb";
            String usuario = "root";
            String contraseña = "";

            Connection conexion = DriverManager.getConnection(url, usuario, contraseña);

            String sql = "SELECT * FROM cancion";

            try (PreparedStatement preparedStatement = conexion.prepareStatement(sql)) {
                ResultSet resultSet = preparedStatement.executeQuery();

                while (resultSet.next()) {
                    Cancion cancion = new Cancion(
                            resultSet.getInt("id_cancion"),
                            resultSet.getString("titulo"),
                            resultSet.getString("autor"),
                            resultSet.getString("disco"),
                            resultSet.getInt("anio"),
                            resultSet.getInt("minuto"),
                            resultSet.getInt("segundo"),
                            resultSet.getString("estilo")
                    );

                    listaCanciones.add(cancion);
                }

                // Llenar tanto la JList como la JTable
                LlenarJList();

            }

            conexion.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void lblModificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModificar1MouseClicked

    private void lblModificar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificar1MouseEntered
        // TODO add your handling code here:
        bgModificar.setBackground(new Color(0x5BC0BE));
    }//GEN-LAST:event_lblModificar1MouseEntered

    private void lblModificar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificar1MouseExited
        // TODO add your handling code here:
        bgModificar.setBackground(new Color(0x1C2541));
    }//GEN-LAST:event_lblModificar1MouseExited

    private void lblModificar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificar1MouseReleased
        // TODO add your handling code here:
        int selectedIndex = JListCanciones.getSelectedIndex();

        if (selectedIndex != -1) {
            //Obtener elemento seleccionado
            String selectedItemFormat = listModelJList.getElementAt(selectedIndex);

            // Obtener el ID del elemento seleccionado
            int selectedId = Integer.parseInt(selectedItemFormat.split("\\.")[0]);

            // Crear una instancia de Modificar2 pasando el ID
            Modificar2 panelModificar2 = new Modificar2(selectedId);
            panelModificar2.setSize(580, 570);
            panelModificar2.setLocation(0, 0);

            // Reemplazar el panel actual con el panel Modificar2
            Container contentPane = getParent();
            contentPane.removeAll();
            contentPane.add(panelModificar2);
            contentPane.revalidate();
            contentPane.repaint();
        } else {
            // Mostrar un mensaje o tomar otra acción si no se ha seleccionado ninguna canción.
        }
    }//GEN-LAST:event_lblModificar1MouseReleased
    private void LlenarJList() {
        listModelJList.clear(); // Limpiar el modelo del JList

        for (Cancion cancion : listaCanciones) {
            String formato = String.format("%d.%s.%s.%s.%d",
                    cancion.getId_cancion(),
                    cancion.getTitulo(),
                    cancion.getAutor(),
                    cancion.getDisco(),
                    cancion.getAnio());

            listModelJList.addElement(formato);
        }

        JListCanciones.setModel(listModelJList); // Actualizar el JList con el nuevo modelo
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar;
    private javax.swing.JList<String> JListCanciones;
    private panels.PanelRound bgModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblModificar1;
    // End of variables declaration//GEN-END:variables
}
