/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

/**
 *
 * @author mosor
 */
public class Reproduccion extends javax.swing.JPanel {

    /**
     * Creates new form Reproduccion
     */
    public Reproduccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelReproductor = new panels.PanelRound();
        lblDisco = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        bgCancion = new panels.PanelRound();
        lblCancion = new javax.swing.JLabel();
        lblDisc = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(234, 246, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelReproductor.setBackground(new java.awt.Color(255, 255, 255));
        panelReproductor.setRoundBottomLeft(50);
        panelReproductor.setRoundBottomRight(50);
        panelReproductor.setRoundTopLeft(50);
        panelReproductor.setRoundTopRight(50);
        panelReproductor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDisco.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblDisco.setText("NOMBRE_DISCO");
        panelReproductor.add(lblDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 190, -1));

        lblAutor.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblAutor.setText("NOMBRE_AUTOR");
        panelReproductor.add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        bgCancion.setBackground(new java.awt.Color(28, 37, 65));
        bgCancion.setRoundBottomLeft(75);
        bgCancion.setRoundBottomRight(75);
        bgCancion.setRoundTopLeft(75);
        bgCancion.setRoundTopRight(75);
        bgCancion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancion.setBackground(new java.awt.Color(255, 255, 255));
        lblCancion.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        lblCancion.setForeground(new java.awt.Color(255, 255, 255));
        lblCancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancion.setText("NOMBRE_CANCION");
        bgCancion.add(lblCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        panelReproductor.add(bgCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 350, 60));

        lblDisc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disc.gif"))); // NOI18N
        panelReproductor.add(lblDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 410, 60));

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        btnPlay.setBorder(null);
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlay.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play_sel.png"))); // NOI18N
        panelReproductor.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next_sel.png"))); // NOI18N
        panelReproductor.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        bg.add(panelReproductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 410, 270));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 570));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private panels.PanelRound bgCancion;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCancion;
    private javax.swing.JLabel lblDisc;
    private javax.swing.JLabel lblDisco;
    private panels.PanelRound panelReproductor;
    // End of variables declaration//GEN-END:variables
}
